<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Username_email</name>
   <tag></tag>
   <elementGuidId>51984bed-038e-421f-88fe-c1429e339a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b930d278-2f55-497a-a9a5-037fa56cb236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>219fcbe6-ca3f-4b61-afc0-8976161c44cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3bbbae53-0198-4d52-ae74-57a74bbf290d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f79e455-3ed7-4a7e-b07a-06687424315d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter here</value>
      <webElementGuid>d5721a23-129c-4768-afa6-b0ecdc3e544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formik</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>18a88f8d-db5e-4272-a6cf-e76d8b65a411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-idXgbr ceRFYq   mod-borderradius</value>
      <webElementGuid>2e834095-858f-4e88-971d-2a56a6ed7da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-hQZdRR bdRgwz&quot;]/div[1]/div[1]/div[@class=&quot;sc-hhhKsR fXsTNV&quot;]/div[@class=&quot;sc-cyRTDc kmmVIH&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout&quot;]/div[@class=&quot;sc-ebbjQI krAOLT&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 sc-jGoKbf kNhMxR&quot;]/div[@class=&quot;sc-dMVFSy clwbOy&quot;]/div[2]/input[@class=&quot;ant-input sc-idXgbr ceRFYq   mod-borderradius&quot;]</value>
      <webElementGuid>108b8baf-c024-45c7-a0ce-876e12c92ace</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>f1fc0a6c-92ef-470e-a4ec-1094e3da29cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/section/section/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>5c349128-8bcf-49ea-88df-33ff150e06a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>043cb284-2ac8-4a43-80c0-534eb492af11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @placeholder = 'Enter here']</value>
      <webElementGuid>dcf72d69-7787-4a54-ae64-60c6bd7c4c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
