<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Username_email</name>
   <tag></tag>
   <elementGuidId>a1f460ca-3710-4feb-9b23-b2c294cf7281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b5313c8-88f2-4246-af75-89cffc268c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa71a7eb-ec3f-4aed-864f-9feda1154fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>772b6df4-d9e6-457d-b95a-10670ed96364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85ab5acc-4e9b-4f84-b259-32976de4a481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter here</value>
      <webElementGuid>2867e09e-b740-454a-8b5e-4de6ce6ebaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formik</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d1756eaa-aec8-4393-8291-67faa20992b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-idXgbr ceRFYq   mod-borderradius</value>
      <webElementGuid>1a0b00ec-f872-4516-a6a6-6b4b851dd3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-hQZdRR bdRgwz&quot;]/div[1]/div[1]/div[@class=&quot;sc-hhhKsR fXsTNV&quot;]/div[@class=&quot;sc-cyRTDc kmmVIH&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout&quot;]/div[@class=&quot;sc-ebbjQI krAOLT&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 sc-jGoKbf kNhMxR&quot;]/div[@class=&quot;sc-dMVFSy clwbOy&quot;]/div[2]/input[@class=&quot;ant-input sc-idXgbr ceRFYq   mod-borderradius&quot;]</value>
      <webElementGuid>a2ca209b-a310-4caa-b34f-191216354c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>94dbc2a8-ad30-4d5f-b7ff-7e6bcafa9767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/section/section/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>fd18199e-e636-4ae3-b06d-3d32e40ce2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>09992583-e5fd-49e1-bc0b-00ba97761ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @placeholder = 'Enter here']</value>
      <webElementGuid>58899486-71af-4b4d-862c-6df1aa8494e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
