<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>5fd9afa7-4de2-4e73-9ee7-b0e7baa79b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f980ced-662d-4484-8658-4daa2fb11c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2dc3ca8e-587b-4035-8b84-cfd8d6ebf7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fLcnxK eelqGM size-default   variant-secondary </value>
      <webElementGuid>2a177060-6a07-48c0-9702-bb3df063f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>navLogin</value>
      <webElementGuid>3ba9ae3b-55e9-429b-859e-1c64ce08cae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-pad</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6526266-c054-4648-9f54-bbbe482d156c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>e872b4be-c377-456f-bd9b-5bbd7ec4af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-eTWrZZ bikXaM&quot;]/div[@class=&quot;sc-gmsKMK eHIEFq&quot;]/div[@class=&quot;sc-jNAkjl enflan&quot;]/div[@class=&quot;sc-jLobnj iOPYCk&quot;]/div[@class=&quot;sc-fENAjM bNkFrL&quot;]/div[@class=&quot;sc-kRkRkg iQaPkQ&quot;]/button[@class=&quot;sc-fLcnxK eelqGM size-default   variant-secondary&quot;]</value>
      <webElementGuid>b2021b00-3639-49c9-958e-4d2b7db9c61d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>345f939e-6da1-45bd-95b6-43af792fcee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>7fdb052c-629c-44cc-8d08-aa4f1968c874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deploy, Track, Optimise, and Automate your Construction Sites today'])[1]/preceding::button[1]</value>
      <webElementGuid>abce2a03-5f49-436a-ba41-d71dfba28871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[2]/preceding::button[1]</value>
      <webElementGuid>7d07c294-d4cf-4c18-89c6-704312c9bdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>71994909-ee6d-42b7-9f36-ea0da1982d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0147b109-6cfd-42e7-956e-7c2bdbae1f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>29634ece-f967-465f-8f7e-98be5acd973d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
