<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>080767c9-4842-431c-a92d-db23ebf9a7e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>416607dd-13d1-4e46-9db0-c51f0150c516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2099232-ec97-4902-bfa3-10ca2897645d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fLcnxK eelqGM size-default   variant-primary </value>
      <webElementGuid>3db4c240-b15e-4414-8021-a9d2420cffdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-pad</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd46cd2b-f44c-45a1-ac81-dbc5b3c2240a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>870901b4-328b-409f-aed1-1eaad1e6f880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-jPNehe lhBabP&quot;]/div[@class=&quot;sc-fXGuyX csfJso&quot;]/div[@class=&quot;sc-iPvCKh jbLnio&quot;]/div[@class=&quot;sc-bbDxtK hNyWgY&quot;]/div[@class=&quot;sc-bPaAec fFNzix&quot;]/div[@class=&quot;sc-hshgAP jPaxvk&quot;]/div[@class=&quot;sc-jneFjB cdqJzk&quot;]/div[@class=&quot;sc-fpaRTa kOaSpg&quot;]/button[@class=&quot;sc-fLcnxK eelqGM size-default   variant-primary&quot;]</value>
      <webElementGuid>adfc965a-5974-411b-8efa-f617f1fe964f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>ff4a0df9-d654-4085-b2fd-03c278135b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div[2]/div[2]/button</value>
      <webElementGuid>195f1b72-7a15-4fe8-9209-0b8c306d2a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Delivery Record'])[1]/following::button[1]</value>
      <webElementGuid>e2253d23-f359-4a90-8a45-9d0a03bdbd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Record'])[1]/following::button[1]</value>
      <webElementGuid>866c466a-1985-464b-9b9c-0f06811cd44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Order No.'])[1]/preceding::button[1]</value>
      <webElementGuid>648ecb40-d9c1-4ae0-891c-01881ad33952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Order Date'])[1]/preceding::button[1]</value>
      <webElementGuid>a6c60b61-62bc-4601-b555-b3e55cd250ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>ab8e2d39-d323-4d63-9beb-7f1d659a5a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f3f82d60-c250-4eb4-a880-4ecb40320779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>9289614f-1e7a-4f45-9289-461bee165906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
