<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select who will verify this delivery _9224c2_1</name>
   <tag></tag>
   <elementGuidId>e0b9a208-f7ef-469b-9c9a-e672b13f28bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-select-search__field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='blake']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5428a002-dc07-4d60-a87b-0562fa9a9bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64bdeba6-cace-408c-bb41-3d0190d00fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-search__field</value>
      <webElementGuid>9541f42b-a193-4527-b888-db78ee2e7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>blake</value>
      <webElementGuid>ac51dfbf-55be-4f8a-8b1d-d60bdcf33f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-jPNehe lhBabP&quot;]/div[@class=&quot;sc-fXGuyX csfJso&quot;]/div[@class=&quot;sc-iPvCKh jbLnio&quot;]/div[@class=&quot;sc-bbDxtK hNyWgY&quot;]/div[@class=&quot;sc-hQZdRR bdRgwz&quot;]/div[1]/div[1]/div[@class=&quot;sc-hhhKsR fXsTNV&quot;]/div[@class=&quot;sc-cyRTDc dTfWzX&quot;]/div[@class=&quot;sc-cJRpLa kAhAVi&quot;]/div[@class=&quot;sc-ibYzZP ixdkZZ&quot;]/div[@class=&quot;ant-col ant-col-20&quot;]/div[@class=&quot;sc-jDfIjF fBSDUD&quot;]/div[1]/div[@class=&quot;sc-enHPVx kqkovd&quot;]/div[@class=&quot;sc-hWdGLs eszyqq&quot;]/div[@class=&quot;sc-gmcCKa iZgaZp project-users-small ant-select ant-select-open ant-select-focused ant-select-enabled ant-select-allow-clear&quot;]/div[@class=&quot;ant-select-selection
            ant-select-selection--single&quot;]/div[@class=&quot;ant-select-selection__rendered&quot;]/div[@class=&quot;ant-select-search ant-select-search--inline&quot;]/div[@class=&quot;ant-select-search__field__wrap&quot;]/input[@class=&quot;ant-select-search__field&quot;]</value>
      <webElementGuid>56ed9148-091e-46d0-b6ca-9f657500089c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='blake']</value>
      <webElementGuid>ccc4a954-e7e8-4cf5-8873-077c0078a3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div[4]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>9faa936a-fd1b-4972-ad3a-db6f02129d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>a4fa9fcf-cb17-40cf-bc04-db7f78b85e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
