<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery Order Date_orderDatetime</name>
   <tag></tag>
   <elementGuidId>1e28c3e7-15d6-4c34-abeb-a0f08a6373c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;orderDatetime&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='orderDatetime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d28a6f5-67bc-46f6-8a78-9ca310e7ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>6f78bff8-9409-46d0-8177-af30a214ec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-calendar-picker-input ant-input</value>
      <webElementGuid>3dce83e5-f410-421c-88e1-d293a05c72c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>orderDatetime</value>
      <webElementGuid>4fd0e5bb-8dbb-4ce4-bce1-5c87455a5cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-jEvhcD karsMF&quot;]/div[@class=&quot;sc-fZqfic cUzlYs&quot;]/div[@class=&quot;sc-dsakmN gIuGeF&quot;]/div[@class=&quot;sc-klEEPK cUqsUD&quot;]/div[@class=&quot;sc-hQZdRR bdRgwz&quot;]/div[1]/div[1]/div[@class=&quot;sc-hhhKsR fXsTNV&quot;]/div[@class=&quot;sc-cyRTDc dTfWzX&quot;]/div[@class=&quot;sc-cJRpLa kAhAVi&quot;]/div[@class=&quot;sc-ibYzZP ixdkZZ&quot;]/div[@class=&quot;ant-col ant-col-20&quot;]/div[@class=&quot;sc-jDfIjF fBSDUD&quot;]/div[1]/div[@class=&quot;sc-enHPVx kqkovd&quot;]/div[1]/div[@class=&quot;sc-hWdGLs eszyqq&quot;]/div[1]/span[@class=&quot;sc-gFvbXA dIEnil   ant-calendar-picker&quot;]/div[1]/input[@class=&quot;ant-calendar-picker-input ant-input&quot;]</value>
      <webElementGuid>28d27863-5ac6-44b4-8453-552174fb9c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='orderDatetime']</value>
      <webElementGuid>63a4a51f-bee1-4897-9c96-fc4fb0d96944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/span/div/input</value>
      <webElementGuid>e0b6addb-04ca-4e10-8603-acde5ce6d8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>3fcb534e-d73d-4f4c-8de6-4330eb1e63d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy' and @name = 'orderDatetime']</value>
      <webElementGuid>eecd1be4-f416-4ffe-bb54-0eda4f719b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
