<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Username_email</name>
   <tag></tag>
   <elementGuidId>e3bfd455-5f48-4443-878f-b9661906370b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd591b3b-37a2-4c69-b8e6-86f9dbb95326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5496b882-73e8-4a5b-bd72-005f86e70275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>394b711b-f9bb-4ae3-af0f-2705740d54c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa3b4c24-27f9-4fd3-b5f9-5d926f3b7ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter here</value>
      <webElementGuid>51f2f594-28c3-49f8-9308-4ef5a1539d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formik</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c03f2d37-45a5-45fe-8fc7-e6e66f9df892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-idXgbr ceRFYq   mod-borderradius</value>
      <webElementGuid>f5bdee02-c99c-4d29-8ef0-a3b29cd93818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-hQZdRR bdRgwz&quot;]/div[1]/div[1]/div[@class=&quot;sc-hhhKsR fXsTNV&quot;]/div[@class=&quot;sc-cyRTDc kmmVIH&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;sc-hWTqMA blrRaf ant-layout&quot;]/div[@class=&quot;sc-ebbjQI krAOLT&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 sc-jGoKbf kNhMxR&quot;]/div[@class=&quot;sc-dMVFSy clwbOy&quot;]/div[2]/input[@class=&quot;ant-input sc-idXgbr ceRFYq   mod-borderradius&quot;]</value>
      <webElementGuid>aa412654-dd85-4df1-b039-238728ddc357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>dafba059-a7e2-4f11-980f-1aea24f089a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/section/section/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>65ad60e6-20f0-48fc-88c4-26127ef47e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>53c2fe67-239f-4e77-875e-6e446e4329ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @placeholder = 'Enter here']</value>
      <webElementGuid>dff14458-c87b-4950-b6c6-cbd15cfc839d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
