<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Installation Record</name>
   <tag></tag>
   <elementGuidId>c8f423f3-d0ec-4800-b41e-354dfcba59bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-fLcnxK.eelqGM.size-default.variant-primary.ant-dropdown-trigger.ant-dropdown-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a55edda0-1cab-4386-820e-21f788cc802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>202e4a10-b11f-4d65-976b-15148d504f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fLcnxK eelqGM size-default   variant-primary ant-dropdown-trigger ant-dropdown-open</value>
      <webElementGuid>4fe05e29-8c1d-484d-ae54-d788bc118dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-pad</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cb06221-7473-4b92-aad5-091c307b9c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Installation Record</value>
      <webElementGuid>15163876-886b-43e4-93b7-0b0bf7ef36a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-dZjHZU gPAfJg&quot;]/div[@class=&quot;sc-nbcfT eDYXiM&quot;]/div[@class=&quot;sc-klEEPK lbVhCT&quot;]/div[@class=&quot;sc-jXeSpT czEfzL&quot;]/div[@class=&quot;sc-bPaAec fFNzix&quot;]/div[@class=&quot;sc-hshgAP fEPIlg&quot;]/div[@class=&quot;sc-jneFjB cdqJzk&quot;]/div[@class=&quot;sc-fpaRTa kOaSpg&quot;]/div[@class=&quot;sc-fQDqYh cLEQjt&quot;]/button[@class=&quot;sc-fLcnxK eelqGM size-default   variant-primary ant-dropdown-trigger ant-dropdown-open&quot;]</value>
      <webElementGuid>85f8bc55-5bc4-4b61-8e9c-64a4a270ff16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>3acaf29b-1dc9-4676-b2d6-314c63e8bc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>6471c8d0-be51-4057-9e23-30b82bddbb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records'])[2]/following::button[1]</value>
      <webElementGuid>c3254a43-b74c-49cd-a8fd-4290a1d7c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records'])[1]/following::button[1]</value>
      <webElementGuid>8a1a1ebf-8edc-4156-bb55-e5ee3f09c1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation Records'])[1]/preceding::button[1]</value>
      <webElementGuid>cdeacde6-217c-4251-8d4e-fe499551e85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Installation Record']/parent::*</value>
      <webElementGuid>dd36e0d9-d171-42df-a936-0e200172026d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>02276ce6-c2e1-47cd-812e-9b415ff204a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Create Installation Record' or . = 'Create Installation Record')]</value>
      <webElementGuid>53f0e757-436a-40c7-901b-ac5feccf1b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
