<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fabrication</name>
   <tag></tag>
   <elementGuidId>cf3b7298-e2a1-4a6e-88f3-12d9de2a0eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-submenu.ant-menu-submenu-inline.sc-jDXXXY.gaJdDp.ant-menu-submenu-active > div.ant-menu-submenu-title > div.sc-dRIUVP.djInLA > span.sc-jOXufW.kLbcwX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Fabrication']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8298a9bb-91a6-4df7-a4df-bec18960fcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jOXufW kLbcwX</value>
      <webElementGuid>718a2204-d570-4e66-9656-9d474d176a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fabrication</value>
      <webElementGuid>d451b99f-7cdc-4114-97f4-4a67a62b7d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-jEvhcD karsMF&quot;]/div[@class=&quot;sc-fZqfic cUzlYs&quot;]/div[@class=&quot;sc-dsakmN gIuGeF&quot;]/div[@class=&quot;sc-dGJyNR botYRo&quot;]/div[@class=&quot;sc-jXeSpT dDiqjE&quot;]/div[@class=&quot;sc-gowCNL kImBNF&quot;]/div[@class=&quot;sc-gkpBqa jATseF&quot;]/div[1]/div[@class=&quot;sc-bSdWI xLPKy&quot;]/ul[@class=&quot;ant-menu sc-iAZqYj coXNoj ant-menu-light ant-menu-root ant-menu-inline&quot;]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline sc-jDXXXY gaJdDp ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]/div[@class=&quot;sc-dRIUVP djInLA&quot;]/span[@class=&quot;sc-jOXufW kLbcwX&quot;]</value>
      <webElementGuid>7e9b2868-bc64-4416-80d5-057c658185d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[3]/div/div/div/div/ul/li[6]/div/div/span[3]</value>
      <webElementGuid>5b0e517b-b5c1-4809-9dd1-95a343f940d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::span[4]</value>
      <webElementGuid>f93ad1c0-6462-4ecc-a683-1aecd590864d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay'])[1]/following::span[8]</value>
      <webElementGuid>deff7a51-49d2-4905-a61d-2b3178e0b491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workforce'])[1]/preceding::span[4]</value>
      <webElementGuid>91bc7e10-1877-4441-b83a-5ee1e5120a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety'])[1]/preceding::span[8]</value>
      <webElementGuid>1619fa7e-6730-43e8-84ec-3798f4103824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fabrication']/parent::*</value>
      <webElementGuid>39394958-e812-4ee8-950b-c396dc8baa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/span[3]</value>
      <webElementGuid>90b5106f-c4fa-4d36-8d08-6f69d073ebcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Fabrication' or . = 'Fabrication')]</value>
      <webElementGuid>028689f5-68c1-4d3f-9ff7-c9604ba4680b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
